// QTipProtocol.h was generated by ProtoGen version 2.18.c

/**

Copyright (c) 2020 DroneCAN

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

**/

#ifndef _QTIPPROTOCOL_H
#define _QTIPPROTOCOL_H

// C++ compilers: don't mangle us
#ifdef __cplusplus
extern "C" {
#endif

/*!
 * \file
 * \mainpage QTip protocol stack
 *

 *
 * The protocol API enumeration is incremented anytime the protocol is changed
 * in a way that affects compatibility with earlier versions of the protocol.
 * The protocol enumeration for this version is: 1
 *
 * The protocol version is 1.0.0
 */

#include <stdint.h>
#include "qtippacket.h"

//! \return the protocol API enumeration
#define getQTipApi() 1

//! \return the protocol version string
#define getQTipVersion() "1.0.0"

typedef enum
{
    PKT_QTIP_CAN_FRAME = 0x10 //!< Serialized CAN packet
} QTipPackets;

//! \return the label of a 'QTipPackets' enum entry, based on its value
const char* QTipPackets_EnumLabel(int value);

/*!
 * CAN frame types
 */
typedef enum
{
    CAN_FRAME_NONE = 0,
    CAN_FRAME_DATA = 1,
    CAN_FRAME_ERROR, 
    CAN_FRAME_RTR,   
    CAN_FRAME_UNKNOWN 
} QTipFrameTypes;


// The prototypes below provide an interface to the packets.
// They are not auto-generated functions, but must be hand-written

//! \return the packet data pointer from the packet
uint8_t* getQTipPacketData(QTIP_Packet_t* pkt);

//! \return the packet data pointer from the packet, const
const uint8_t* getQTipPacketDataConst(const QTIP_Packet_t* pkt);

//! Complete a packet after the data have been encoded
void finishQTipPacket(QTIP_Packet_t* pkt, int size, uint32_t packetID);

//! \return the size of a packet from the packet header
int getQTipPacketSize(const QTIP_Packet_t* pkt);

//! \return the ID of a packet from the packet header
uint32_t getQTipPacketID(const QTIP_Packet_t* pkt);

#ifdef __cplusplus
}
#endif
#endif
